name: Python Workflow
on: workflow_dispatch
jobs: 
  my-first-job:
    runs-on: ubuntu-latest
    outputs:
      job1_op: 'Output from job1'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Run Script
        run: python main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-output
          path: src/

      - name: Set Output
        id: set-output
        run : echo name=Vicky >> $GITHUB_OUTPUT

      - name: Access Output
        run: echo "Output value is ${{ steps.set-output.outputs.name }}"

  my-second-job:
    needs: my-first-job
    steps:
      - name: Access output var from job 1
        run : echo "Job1 Output : ${{ needs.my-first-job.outputs.job1_op }}"