name: Python Workflow
on: workflow_dispatch
jobs: 
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Run Script
        run: python main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-output
          path: src/

      - name: Context Variable
        run : echo "${{ github }}"

  second-job:
    needs: my-first-job
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-output
          path: downloaded/

      - name: List downloaded files
        run: |
              ls -R downloaded
              cat result.txt